app.netbadge.base-url=${APP_BASE_URL:https://abet-faculty-vitae-backend-0a93df3b12de.herokuapp.com}
app.netbadge.idp-metadata-uri=${NETBADGE_IDP_METADATA_URI:https://shibidp.its.virginia.edu/idp/shibboleth/uva-idp-metadata.xml}

server.forward-headers-strategy=native
